name: Unit Tests

on: 

  push:
    branches: [main]
  
  pull_request:
    branches: [main]


  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Set up requirements
        run: |
          python3 -m pip install --upgrade pip
          make install-dev

      - name: Run tests
        run: |
          python3 -m pytest --import-mode=append tests/
